{{- if .Values.txSender.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "txSenderName" . }}
  labels:
    app: coprocessor-tx-sender
    app.kubernetes.io/name: {{ include "txSenderName" . }}
spec:
  type: ClusterIP
  selector:
    app: coprocessor-tx-sender
    app.kubernetes.io/name: {{ include "txSenderName" . }}
  ports:
    - name: metrics
      port: {{ .Values.txSender.ports.metrics }}
      targetPort: metrics
    - name: healthcheck
      port: {{ .Values.txSender.ports.healthcheck }}
      targetPort: healthcheck
{{- end }}
